export const categoryDetails = {
  electronics: {
    slug: "electronics",
    title: "Electronics",
    subtitle: "Buy & Sell New and Used Electronics at Best Prices",
    icon: "Tv",
    bannerGradient: "from-blue-600 via-indigo-600 to-blue-800",
    subcategories: ["TV & Audio", "Laptops & Computers", "Cameras & Optics", "Audio & Headphones", "Gaming Consoles", "Home Appliances"],
    brands: ["Sony", "Samsung", "LG", "Apple", "Dell", "HP", "Bose", "Canon", "JBL"],
  },
  mobiles: {
    slug: "mobiles",
    title: "Mobiles & Accessories",
    subtitle: "Find Great Deals on Smartphones, Tablets & Accessories",
    icon: "Smartphone",
    bannerGradient: "from-sky-600 via-blue-600 to-indigo-700",
    subcategories: ["Smartphones", "iPhones", "Tablets", "Smartwatches", "Mobile Accessories", "Power Banks"],
    brands: ["Apple", "Samsung", "OnePlus", "Google", "Xiaomi", "Realme", "Vivo", "Nothing"],
  },
  vehicles: {
    slug: "vehicles",
    title: "Vehicles",
    subtitle: "Used Cars, Bikes, Scooters & Spare Parts from Verified Sellers",
    icon: "Car",
    bannerGradient: "from-rose-600 via-red-600 to-amber-600",
    subcategories: ["Cars", "Motorcycles", "Scooters", "Bicycles", "Commercial Vehicles", "Spare Parts"],
    brands: ["Honda", "Maruti Suzuki", "Hyundai", "Royal Enfield", "KTM", "Yamaha", "Tata", "Mahindra", "BMW"],
  },
  properties: {
    slug: "properties",
    title: "Properties",
    subtitle: "Buy, Sell & Rent Flats, Houses, Plots & Commercial Spaces",
    icon: "Home",
    bannerGradient: "from-amber-600 via-orange-600 to-red-600",
    subcategories: ["Flats & Apartments", "Houses & Villas", "Land & Plots", "Commercial Office", "PG & Hostels", "Shops & Showrooms"],
    brands: ["DLF", "Godrej Properties", "Prestige", "Sobha", "Unitech", "Lodha"],
  },
  furniture: {
    slug: "furniture",
    title: "Furniture & Home Decor",
    subtitle: "Upgrade Your Home with Quality Pre-owned Furniture",
    icon: "Armchair",
    bannerGradient: "from-emerald-600 via-teal-600 to-cyan-700",
    subcategories: ["Sofa & Recliners", "Beds & Mattresses", "Dining Tables", "Wardrobes", "Study Tables", "Office Chairs"],
    brands: ["IKEA", "Godrej Interio", "Pepperfry", "Urban Ladder", "RoyalOak", "Durian"],
  },
  fashion: {
    slug: "fashion",
    title: "Fashion & Lifestyle",
    subtitle: "Trendy Clothing, Footwear, Watches & Accessories",
    icon: "Shirt",
    bannerGradient: "from-purple-600 via-fuchsia-600 to-pink-600",
    subcategories: ["Men's Wear", "Women's Wear", "Footwear", "Watches & Jewelry", "Bags & Luggage", "Eyewear"],
    brands: ["Nike", "Adidas", "Puma", "Fossil", "Zara", "Levi's", "Ray-Ban", "Casio"],
  },
  books: {
    slug: "books",
    title: "Books, Hobbies & Sports",
    subtitle: "Pre-loved Books, Educational Materials, Musical Instruments & Sports Equipment",
    icon: "BookOpen",
    bannerGradient: "from-teal-600 via-emerald-600 to-green-700",
    subcategories: ["Textbooks & Exam Prep", "Fiction & Novels", "Comics & Manga", "Musical Instruments", "Fitness & Sports", "Board Games"],
    brands: ["McGraw Hill", "Pearson", "Yamaha Music", "Decathlon", "Cosco", "Penguin"],
  },
  services: {
    slug: "services",
    title: "Services & Repairs",
    subtitle: "Trusted Local Technicians, Cleaners, Contractors & Designers",
    icon: "Wrench",
    bannerGradient: "from-indigo-600 via-purple-600 to-violet-700",
    subcategories: ["Home Cleaning", "AC & Appliance Repair", "Interior Design", "Car Servicing", "Packers & Movers", "Event Management"],
    brands: ["Urban Company", "BechDal Verified", "Local Expert", "ProClean"],
  },
  pets: {
    slug: "pets",
    title: "Pets & Pet Care",
    subtitle: "Pet Supplies, Accessories, Aquariums & Veterinary Services",
    icon: "Dog",
    bannerGradient: "from-amber-500 via-yellow-600 to-amber-700",
    subcategories: ["Dogs & Accessories", "Cats & Accessories", "Aquarium & Fish", "Birds & Cages", "Pet Food & Care"],
    brands: ["Royal Canin", "Pedigree", "Whiskas", "Drools", "Fluval"],
  },
};

export const categoryProducts = {
  electronics: [
    {
      id: 301,
      title: "Sony Bravia 55 inch 4K Ultra HD Smart LED TV",
      price: "44,500",
      originalPrice: "69,900",
      discount: "36% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "3 hours ago",
      image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Like New",
      brand: "Sony",
      subcategory: "TV & Audio",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: 302,
      title: "Dell XPS 13 i7 11th Gen - 16GB RAM / 512GB SSD",
      price: "68,000",
      originalPrice: "95,000",
      discount: "28% OFF",
      location: "Salt Lake, Kolkata",
      postedTime: "5 hours ago",
      image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Excellent",
      brand: "Dell",
      subcategory: "Laptops & Computers",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 303,
      title: "Canon EOS 1500D DSLR Camera with 18-55mm Lens",
      price: "24,999",
      originalPrice: "34,995",
      discount: "28% OFF",
      location: "Mumbai, Maharashtra",
      postedTime: "1 day ago",
      image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Like New",
      brand: "Canon",
      subcategory: "Cameras & Optics",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.6,
    },
    {
      id: 304,
      title: "Bose QuietComfort 45 Wireless Noise Cancelling Headphones",
      price: "18,500",
      originalPrice: "29,900",
      discount: "38% OFF",
      location: "Bangalore, Karnataka",
      postedTime: "2 days ago",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Brand New",
      brand: "Bose",
      subcategory: "Audio & Headphones",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: false,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 305,
      title: "Sony PlayStation 5 Console (Disc Edition) + 2 Controllers",
      price: "42,000",
      originalPrice: "54,990",
      discount: "23% OFF",
      location: "Delhi NCR",
      postedTime: "4 hours ago",
      image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Like New",
      brand: "Sony",
      subcategory: "Gaming Consoles",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.7,
    },
    {
      id: 306,
      title: "LG 1.5 Ton 5 Star Dual Inverter Split AC",
      price: "26,500",
      originalPrice: "44,000",
      discount: "40% OFF",
      location: "Pune, Maharashtra",
      postedTime: "6 hours ago",
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Good",
      brand: "LG",
      subcategory: "Home Appliances",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.5,
    },
    {
      id: 307,
      title: "JBL PartyBox 110 Portable Bluetooth Speaker",
      price: "21,000",
      originalPrice: "31,999",
      discount: "34% OFF",
      location: "Hyderabad, Telangana",
      postedTime: "12 hours ago",
      image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=600&auto=format&fit=crop",
      badge: "Sale",
      isPremium: false,
      isFeatured: false,
      condition: "Excellent",
      brand: "JBL",
      subcategory: "Audio & Headphones",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: 308,
      title: "Apple iPad Air 5th Gen M1 Chip (64GB Wi-Fi)",
      price: "43,000",
      originalPrice: "59,900",
      discount: "28% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "1 day ago",
      image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "Apple",
      subcategory: "Laptops & Computers",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: false,
      deliveryAvailable: true,
      rating: 5.0,
    },
  ],
  mobiles: [
    {
      id: 1,
      title: "iPhone 14 Pro Max 256GB - Deep Purple",
      price: "74,999",
      originalPrice: "1,39,900",
      discount: "46% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "2 hours ago",
      image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "Apple",
      subcategory: "iPhones",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 105,
      title: "Apple iPhone 13 128GB - Blue",
      price: "42,999",
      originalPrice: "54,900",
      discount: "22% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "5 hours ago",
      image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Excellent",
      brand: "Apple",
      subcategory: "iPhones",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: 401,
      title: "Samsung Galaxy S23 Ultra 5G (12GB RAM, 256GB)",
      price: "78,500",
      originalPrice: "1,24,999",
      discount: "37% OFF",
      location: "Mumbai, Maharashtra",
      postedTime: "1 hour ago",
      image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: true,
      isFeatured: true,
      condition: "Brand New",
      brand: "Samsung",
      subcategory: "Smartphones",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 402,
      title: "OnePlus 11 5G (Titan Black, 16GB RAM)",
      price: "41,999",
      originalPrice: "61,999",
      discount: "32% OFF",
      location: "Delhi NCR",
      postedTime: "4 hours ago",
      image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Like New",
      brand: "OnePlus",
      subcategory: "Smartphones",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.7,
    },
    {
      id: 403,
      title: "Google Pixel 7a 5G (Sea, 128GB Storage)",
      price: "27,500",
      originalPrice: "43,999",
      discount: "37% OFF",
      location: "Bangalore, Karnataka",
      postedTime: "6 hours ago",
      image: "https://images.unsplash.com/photo-1592755219588-d4bf92a0a2eb?q=80&w=600&auto=format&fit=crop",
      badge: "Sale",
      isPremium: false,
      isFeatured: false,
      condition: "Excellent",
      brand: "Google",
      subcategory: "Smartphones",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.6,
    },
    {
      id: 404,
      title: "Apple Watch Series 8 GPS 45mm Midnight Aluminium",
      price: "24,000",
      originalPrice: "45,900",
      discount: "47% OFF",
      location: "Pune, Maharashtra",
      postedTime: "Yesterday",
      image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "Apple",
      subcategory: "Smartwatches",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: false,
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: 405,
      title: "Xiaomi 13 Pro (12GB RAM, 256GB Ceramic Black)",
      price: "49,000",
      originalPrice: "79,999",
      discount: "38% OFF",
      location: "Hyderabad, Telangana",
      postedTime: "2 days ago",
      image: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Good",
      brand: "Xiaomi",
      subcategory: "Smartphones",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.4,
    },
  ],
  vehicles: [
    {
      id: 101,
      title: "Honda City 1.5 VX CVT 2020 Model - Single Owner",
      price: "7,25,000",
      originalPrice: "11,50,000",
      discount: "37% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "1 week ago",
      image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=600&auto=format&fit=crop",
      badge: "FEATURED",
      isFeatured: true,
      isPremium: true,
      condition: "Excellent",
      brand: "Honda",
      subcategory: "Cars",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.9,
    },
    {
      id: 2,
      title: "Hyundai i20 Asta 1.2 Petrol 2021",
      price: "6,45,000",
      originalPrice: "8,90,000",
      discount: "27% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "5 hours ago",
      image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "Hyundai",
      subcategory: "Cars",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.8,
    },
    {
      id: 3,
      title: "Royal Enfield Classic 350 Stealth Black 2022",
      price: "1,65,000",
      originalPrice: "2,15,000",
      discount: "23% OFF",
      location: "Howrah, West Bengal",
      postedTime: "1 day ago",
      image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Excellent",
      brand: "Royal Enfield",
      subcategory: "Motorcycles",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.7,
    },
    {
      id: 501,
      title: "Maruti Suzuki Swift ZXi Petrol 2022",
      price: "5,80,000",
      originalPrice: "7,50,000",
      discount: "22% OFF",
      location: "Mumbai, Maharashtra",
      postedTime: "3 hours ago",
      image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Like New",
      brand: "Maruti Suzuki",
      subcategory: "Cars",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 502,
      title: "KTM Duke 390 BS6 - Low Mileage 2021",
      price: "2,10,000",
      originalPrice: "2,95,000",
      discount: "28% OFF",
      location: "Bangalore, Karnataka",
      postedTime: "6 hours ago",
      image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Excellent",
      brand: "KTM",
      subcategory: "Motorcycles",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.8,
    },
    {
      id: 503,
      title: "Yamaha MT-15 Version 2.0 Ice Fluo 2023",
      price: "1,35,000",
      originalPrice: "1,68,000",
      discount: "19% OFF",
      location: "Delhi NCR",
      postedTime: "12 hours ago",
      image: "https://images.unsplash.com/photo-1623861517329-a1b742880f08?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Like New",
      brand: "Yamaha",
      subcategory: "Motorcycles",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.6,
    },
  ],
  properties: [
    {
      id: 4,
      title: "2 BHK Luxury Flat for Sale in New Town",
      price: "32,00,000",
      originalPrice: "38,00,000",
      discount: "15% OFF",
      location: "New Town, Kolkata",
      postedTime: "1 day ago",
      image: "https://images.unsplash.com/photo-1560518884-ce58750a5656?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Brand New",
      brand: "Godrej Properties",
      subcategory: "Flats & Apartments",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.9,
    },
    {
      id: 102,
      title: "3 BHK Apartment with Pool & Gym Access",
      price: "45,00,000",
      originalPrice: "52,00,000",
      discount: "13% OFF",
      location: "Salt Lake, Kolkata",
      postedTime: "3 days ago",
      image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=600&auto=format&fit=crop",
      badge: "FEATURED",
      isFeatured: true,
      isPremium: true,
      condition: "Like New",
      brand: "DLF",
      subcategory: "Flats & Apartments",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.8,
    },
    {
      id: 601,
      title: "Modern Commercial Office Space 1200 Sq.Ft.",
      price: "85,000 /month",
      originalPrice: "1,00,000",
      discount: "15% OFF",
      location: "Cyber City, Gurgaon",
      postedTime: "2 hours ago",
      image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Excellent",
      brand: "Unitech",
      subcategory: "Commercial Office",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.9,
    },
    {
      id: 602,
      title: "Independent 3 BHK Villa with Private Garden",
      price: "89,00,000",
      originalPrice: "1,05,00,000",
      discount: "15% OFF",
      location: "Whitefield, Bangalore",
      postedTime: "4 days ago",
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Brand New",
      brand: "Prestige",
      subcategory: "Houses & Villas",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 5.0,
    },
  ],
  furniture: [
    {
      id: 5,
      title: "3 Seater Fabric Sofa Set in Navy Blue",
      price: "12,500",
      originalPrice: "24,000",
      discount: "47% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "2 days ago",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "IKEA",
      subcategory: "Sofa & Recliners",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.7,
    },
    {
      id: 202,
      title: "Solid Teak Wood 6 Seater Dining Table Set",
      price: "8,500",
      originalPrice: "18,900",
      discount: "55% OFF",
      location: "Rajarhat, Kolkata",
      postedTime: "1 hour ago",
      image: "https://images.unsplash.com/photo-1604578762246-41134e37f9cc?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Good",
      brand: "Urban Ladder",
      subcategory: "Dining Tables",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.5,
    },
    {
      id: 701,
      title: "King Size Hydraulic Storage Bed with Mattress",
      price: "19,999",
      originalPrice: "38,000",
      discount: "47% OFF",
      location: "Mumbai, Maharashtra",
      postedTime: "5 hours ago",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Excellent",
      brand: "Pepperfry",
      subcategory: "Beds & Mattresses",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: 702,
      title: "4 Door Wooden Wardrobe with Mirror",
      price: "14,000",
      originalPrice: "26,500",
      discount: "47% OFF",
      location: "Pune, Maharashtra",
      postedTime: "Yesterday",
      image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Good",
      brand: "Godrej Interio",
      subcategory: "Wardrobes",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.4,
    },
  ],
  fashion: [
    {
      id: 801,
      title: "Nike Air Jordan 1 Retro High OG - Size 9 UK",
      price: "11,500",
      originalPrice: "16,995",
      discount: "32% OFF",
      location: "Bangalore, Karnataka",
      postedTime: "3 hours ago",
      image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: true,
      isFeatured: true,
      condition: "Brand New",
      brand: "Nike",
      subcategory: "Footwear",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 802,
      title: "Fossil Gen 6 Touchscreen Smartwatch Leather Strap",
      price: "9,999",
      originalPrice: "23,995",
      discount: "58% OFF",
      location: "Delhi NCR",
      postedTime: "6 hours ago",
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Like New",
      brand: "Fossil",
      subcategory: "Watches & Jewelry",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.7,
    },
    {
      id: 803,
      title: "Genuine Black Biker Leather Jacket for Men",
      price: "4,200",
      originalPrice: "8,500",
      discount: "50% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "Yesterday",
      image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=600&auto=format&fit=crop",
      badge: "Sale",
      isPremium: false,
      isFeatured: false,
      condition: "Excellent",
      brand: "Zara",
      subcategory: "Men's Wear",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.6,
    },
  ],
  books: [
    {
      id: 901,
      title: "UPSC Civil Services Complete Exam Prep Bundle (12 Books)",
      price: "2,499",
      originalPrice: "6,500",
      discount: "61% OFF",
      location: "Delhi NCR",
      postedTime: "2 hours ago",
      image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "McGraw Hill",
      subcategory: "Textbooks & Exam Prep",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 902,
      title: "Yamaha F310 Acoustic Guitar with Gig Bag",
      price: "6,800",
      originalPrice: "10,990",
      discount: "38% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "5 hours ago",
      image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?q=80&w=600&auto=format&fit=crop",
      badge: "PREMIUM",
      isPremium: true,
      isFeatured: true,
      condition: "Excellent",
      brand: "Yamaha Music",
      subcategory: "Musical Instruments",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.8,
    },
    {
      id: 903,
      title: "One Piece Manga Box Set 1 (Volumes 1-23)",
      price: "7,500",
      originalPrice: "14,999",
      discount: "50% OFF",
      location: "Mumbai, Maharashtra",
      postedTime: "1 day ago",
      image: "https://images.unsplash.com/photo-1618365908648-e71bd5716cba?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Brand New",
      brand: "Penguin",
      subcategory: "Comics & Manga",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: false,
      deliveryAvailable: true,
      rating: 5.0,
    },
  ],
  services: [
    {
      id: 1001,
      title: "Full House Deep Cleaning & Sanitization Service",
      price: "1,999",
      originalPrice: "3,500",
      discount: "43% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "Available Today",
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: true,
      isFeatured: true,
      condition: "Brand New",
      brand: "BechDal Verified",
      subcategory: "Home Cleaning",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.9,
    },
    {
      id: 1002,
      title: "Split AC Gas Refill & General Servicing Package",
      price: "599",
      originalPrice: "1,200",
      discount: "50% OFF",
      location: "Mumbai, Maharashtra",
      postedTime: "Same Day Visit",
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=600&auto=format&fit=crop",
      badge: "Sale",
      isPremium: false,
      isFeatured: false,
      condition: "Excellent",
      brand: "Local Expert",
      subcategory: "AC & Appliance Repair",
      sellerType: "Verified Dealer",
      isVerifiedSeller: true,
      isNegotiable: false,
      deliveryAvailable: true,
      rating: 4.7,
    },
  ],
  pets: [
    {
      id: 1101,
      title: "Custom 3 Feet Aquascaped Glass Fish Tank with LED & Filter",
      price: "7,500",
      originalPrice: "14,000",
      discount: "46% OFF",
      location: "Kolkata, West Bengal",
      postedTime: "Yesterday",
      image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?q=80&w=600&auto=format&fit=crop",
      badge: "Verified",
      isPremium: false,
      isFeatured: true,
      condition: "Like New",
      brand: "Fluval",
      subcategory: "Aquarium & Fish",
      sellerType: "Individual",
      isVerifiedSeller: true,
      isNegotiable: true,
      deliveryAvailable: false,
      rating: 4.8,
    },
    {
      id: 1102,
      title: "Heavy Duty Foldable Metal Pet Crate for Large Dogs",
      price: "3,200",
      originalPrice: "5,800",
      discount: "45% OFF",
      location: "Bangalore, Karnataka",
      postedTime: "3 days ago",
      image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=600&auto=format&fit=crop",
      badge: null,
      isPremium: false,
      isFeatured: false,
      condition: "Good",
      brand: "Royal Canin",
      subcategory: "Dogs & Accessories",
      sellerType: "Individual",
      isVerifiedSeller: false,
      isNegotiable: true,
      deliveryAvailable: true,
      rating: 4.6,
    },
  ],
};

export const popularSearchTags = [
  "iPhone", "Samsung", "MacBook", "Royal Enfield", "Honda City", 
  "Sofa", "Laptop", "AC", "TV", "DSLR Camera", "PlayStation 5", 
  "Flat for Rent", "Dining Table", "Nike Shoes", "Guitar"
];
