export const notifications = [
  {
    id: "notif_1",
    type: "message",
    title: "New Message",
    description: "Rahul Sharma sent you a message regarding 'iPhone 13 Pro Max 256GB'.",
    timestamp: "2 mins ago",
    isUnread: true,
    actionLink: "/chat/rahul-sharma",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "notif_2",
    type: "offer",
    title: "Offer Received",
    description: "You received a new offer of ₹6,00,000 for your listing 'Hyundai i20 Asta 2021'.",
    timestamp: "1 hour ago",
    isUnread: true,
    actionLink: "/offers",
  },
  {
    id: "notif_3",
    type: "alert",
    title: "Listing Published",
    description: "Congratulations! Your listing 'Royal Enfield Classic 350' is now live.",
    timestamp: "3 hours ago",
    isUnread: false,
    actionLink: "/product/BD12345678",
  },
  {
    id: "notif_4",
    type: "promo",
    title: "Premium Ad Discount",
    description: "Get 50% off on Premium Ads this weekend! Sell your items faster.",
    timestamp: "1 day ago",
    isUnread: false,
    actionLink: "/premium",
  },
  {
    id: "notif_5",
    type: "message",
    title: "New Message",
    description: "Priya Patel sent you a message regarding '3 Seater Sofa Set'.",
    timestamp: "2 days ago",
    isUnread: false,
    actionLink: "/chat/priya-patel",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "notif_6",
    type: "alert",
    title: "Price Drop Alert",
    description: "An item in your wishlist 'MacBook Air M1' has dropped in price by ₹2,000.",
    timestamp: "3 days ago",
    isUnread: false,
    actionLink: "/wishlist",
  }
];
