export const sellCategories = [
  {
    id: "electronics",
    name: "Electronics",
    icon: "MonitorSmartphone",
    description: "Mobiles, Laptops, Cameras, TVs, etc.",
    subcategories: [
      "Laptop",
      "Camera",
      "TV",
      "Gaming Console",
      "Speaker",
      "Accessories",
      "Smartwatch",
    ],
  },
  {
    id: "mobiles",
    name: "Mobiles",
    icon: "Smartphone",
    description: "Mobile phones, Tablets, Accessories",
    subcategories: [
      "Mobile Phones",
      "Tablets",
      "Accessories",
      "Wearables",
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles",
    icon: "Car",
    description: "Cars, Bikes, Scooters, Commercial",
    subcategories: [
      "Cars",
      "Motorcycles",
      "Scooters",
      "Bicycles",
      "Commercial Vehicles",
      "Spare Parts",
    ],
  },
  {
    id: "furniture",
    name: "Furniture",
    icon: "Sofa",
    description: "Sofas, Beds, Wardrobes, Tables",
    subcategories: [
      "Sofa & Dining",
      "Beds & Wardrobes",
      "Home Decor & Garden",
      "Kids Furniture",
      "Other Household Items",
    ],
  },
  {
    id: "fashion",
    name: "Fashion",
    icon: "Shirt",
    description: "Men, Women, Kids Clothing & Accessories",
    subcategories: [
      "Men",
      "Women",
      "Kids",
      "Watches",
      "Footwear",
      "Bags & Luggage",
    ],
  },
  {
    id: "books",
    name: "Books",
    icon: "BookOpen",
    description: "Fiction, Non-fiction, Academic, Magazines",
    subcategories: [
      "Fiction",
      "Non-fiction",
      "Academic",
      "Magazines",
      "Comics",
    ],
  },
  {
    id: "pets",
    name: "Pet Items",
    icon: "Dog",
    description: "Dogs, Cats, Birds, Aquariums & Pet Supplies",
    subcategories: [
      "Dogs",
      "Cats",
      "Birds",
      "Aquariums",
      "Pet Accessories",
      "Other Pets",
    ],
  },
  {
    id: "properties",
    name: "Properties",
    icon: "Home",
    description: "For Rent, For Sale, Commercial",
    subcategories: [
      "Residential",
      "Commercial",
      "Plot",
      "Hotels/Resorts",
      "PG & Guest Houses",
      "Other Properties",
    ],
  },
  {
    id: "jobs",
    name: "Jobs",
    icon: "Briefcase",
    description: "Data entry, Sales, BPO, Marketing",
    subcategories: [
      "Data entry & Back office",
      "Sales & Marketing",
      "BPO & Telecaller",
      "Delivery & Collection",
      "Teacher",
      "Cook",
      "Receptionist & Front office",
      "Operator & Technician",
      "IT Engineer & Developer",
      "Hotel & Travel Executive",
      "Accountant",
      "Designer",
      "Other Jobs",
    ],
  },
  {
    id: "services",
    name: "Services",
    icon: "Wrench",
    description: "Drivers, Tutors, Cleaning, Repairs",
    subcategories: [
      "Education & Classes",
      "Tours & Travel",
      "Electronics & Computer Repair",
      "Health & Beauty",
      "Legal & Documentation",
      "Movers & Packers",
      "Drivers & Taxi",
      "Maids & Domestic Help",
      "Other Services",
    ],
  },
  {
    id: "kids-accessories",
    name: "Kids Accessories",
    icon: "Gamepad2",
    description: "Toys, Baby Care, Strollers & Kids Clothing",
    subcategories: [
      "Educational Toys & Games",
      "Baby Strollers & Prams",
      "Kids Clothing & Footwear",
      "Dolls & Action Figures",
      "Nursery & Baby Care",
      "Other Kids Accessories",
    ],
  },
  {
    id: "fitness-gym-music",
    name: "Fitness, Gym & Musical Instruments",
    icon: "Dumbbell",
    description: "Gym equipment, Fitness gear & Musical instruments",
    subcategories: [
      "Gym Equipment & Treadmills",
      "Weights & Barbells",
      "Guitars & String Instruments",
      "Keyboards & Pianos",
      "Drums & Percussion",
      "Fitness Accessories",
      "Other Musical Instruments",
    ],
  },
  {
    id: "pet-products",
    name: "Pet Products",
    icon: "ShoppingBag",
    description: "Pet Food, Leashes, Collars, Toys, Aquariums",
    subcategories: [
      "Pet Food",
      "Leashes & Collars",
      "Cages & Kennels",
      "Aquarium Filters",
      "Pet Toys",
      "Other Pet Products"
    ],
  },
  {
    id: "agricultural-products",
    name: "Agricultural Products",
    icon: "Leaf",
    description: "Crops, Fertilizers, Seeds, Farming Tools",
    subcategories: [
      "Organic Fertilizers",
      "Seeds & Bulbs",
      "Crop Protection",
      "Farming Tools",
      "Fresh Harvests",
      "Other Agriculture"
    ],
  },
  {
    id: "construction-equipment",
    name: "Construction Equipment",
    icon: "Hammer",
    description: "Machinery, Concrete Mixers, Power Tools",
    subcategories: [
      "Excavators & Backhoes",
      "Concrete Mixers",
      "Power Tools",
      "Safety Equipment",
      "Scaffolding",
      "Other Equipment"
    ],
  },
  {
    id: "office-equipment",
    name: "Office Equipment",
    icon: "Printer",
    description: "Printers, Projectors, Paper Shredders, Filing Cabinets",
    subcategories: [
      "Printers & Scanners",
      "Projectors",
      "Paper Shredders",
      "Office Desks & Chairs",
      "Filing Cabinets",
      "Other Office Items"
    ],
  },
];

export const dynamicSpecifications = {
  mobiles: [
    { name: "brand", label: "Brand", type: "text", required: true },
    { name: "storage", label: "Storage (GB)", type: "number", required: true },
    { name: "ram", label: "RAM (GB)", type: "number", required: true },
    { name: "batteryHealth", label: "Battery Health (%)", type: "number", required: false },
    { name: "processor", label: "Processor", type: "text", required: false },
    { name: "screenSize", label: "Screen Size (inches)", type: "number", required: false },
    { name: "imeiAvailable", label: "IMEI Available", type: "checkbox", required: false },
  ],
  vehicles: [
    { name: "brand", label: "Brand", type: "text", required: true },
    { name: "fuelType", label: "Fuel Type", type: "select", options: ["Petrol", "Diesel", "CNG", "Electric", "Hybrid"], required: true },
    { name: "transmission", label: "Transmission", type: "select", options: ["Manual", "Automatic"], required: true },
    { name: "owner", label: "No. of Owners", type: "select", options: ["1st", "2nd", "3rd", "4th+"], required: true },
    { name: "kmDriven", label: "KM Driven", type: "number", required: true },
    { name: "insurance", label: "Insurance Valid Till", type: "date", required: false },
    { name: "rcAvailable", label: "RC Available", type: "checkbox", required: false },
    { name: "registrationYear", label: "Registration Year", type: "number", required: true },
  ],
  properties: [
    { name: "bedrooms", label: "Bedrooms", type: "select", options: ["1", "2", "3", "4", "4+"], required: true },
    { name: "bathrooms", label: "Bathrooms", type: "select", options: ["1", "2", "3", "4+"], required: true },
    { name: "area", label: "Built-up Area (sq.ft)", type: "number", required: true },
    { name: "furnished", label: "Furnishing", type: "select", options: ["Furnished", "Semi-Furnished", "Unfurnished"], required: true },
    { name: "parking", label: "Parking Available", type: "checkbox", required: false },
    { name: "facing", label: "Facing", type: "select", options: ["East", "West", "North", "South", "North-East", "North-West", "South-East", "South-West"], required: false },
  ],
  books: [
    { name: "author", label: "Author", type: "text", required: true },
    { name: "publisher", label: "Publisher", type: "text", required: false },
    { name: "edition", label: "Edition/Year", type: "text", required: false },
    { name: "language", label: "Language", type: "text", required: true },
  ],
  furniture: [
    { name: "material", label: "Material", type: "text", required: false },
    { name: "dimensions", label: "Dimensions (L x W x H)", type: "text", required: false },
    { name: "assemblyRequired", label: "Assembly Required", type: "checkbox", required: false },
    { name: "color", label: "Color", type: "text", required: false },
  ],
  jobs: [
    { name: "salary", label: "Salary/Compensation (Monthly)", type: "number", required: true },
    { name: "jobType", label: "Job Type", type: "select", options: ["Full-time", "Part-time", "Contract", "Internship"], required: true },
    { name: "experience", label: "Experience Required (Years)", type: "text", required: false },
    { name: "openings", label: "No. of Openings", type: "number", required: false },
  ],
  services: [
    { name: "serviceType", label: "Service Type", type: "text", required: true },
    { name: "pricingType", label: "Pricing Type", type: "select", options: ["Hourly Rate", "Fixed Flat Fee", "Contact for Quote"], required: true },
  ],
  pets: [
    { name: "petType", label: "Pet Type", type: "select", options: ["Dog", "Cat", "Bird", "Fish", "Rabbit", "Other"], required: true },
    { name: "breed", label: "Breed", type: "text", required: false },
    { name: "age", label: "Age (Months/Years)", type: "text", required: false },
    { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Pair", "Unspecified"], required: false },
    { name: "vaccinationStatus", label: "Vaccination Status", type: "select", options: ["Fully Vaccinated", "Partially Vaccinated", "Not Vaccinated"], required: true },
  ],
  "pet-products": [
    { name: "productType", label: "Product Type", type: "text", required: true },
    { name: "brand", label: "Brand", type: "text", required: false },
    { name: "condition", label: "Condition", type: "select", options: ["Brand New", "Like New", "Excellent", "Good", "Fair"], required: true },
  ],
  "agricultural-products": [
    { name: "productType", label: "Product Type", type: "text", required: true },
    { name: "usage", label: "Primary Usage", type: "text", required: false },
    { name: "brand", label: "Brand/Manufacturer", type: "text", required: false },
    { name: "condition", label: "Condition", type: "select", options: ["Brand New", "Used/Pre-owned"], required: true },
  ],
  "construction-equipment": [
    { name: "equipmentType", label: "Equipment Type", type: "text", required: true },
    { name: "brand", label: "Brand/Manufacturer", type: "text", required: true },
    { name: "operatingHours", label: "Operating Hours (Hrs)", type: "number", required: true },
    { name: "registrationYear", label: "Year of Manufacture", type: "number", required: true },
  ],
  "office-equipment": [
    { name: "equipmentType", label: "Equipment Type", type: "text", required: true },
    { name: "brand", label: "Brand/Manufacturer", type: "text", required: false },
    { name: "warranty", label: "Warranty Available", type: "select", options: ["Yes, Active Warranty", "No Warranty", "Expired"], required: true },
  ],
};
