export const sellCategories = [
  {
    id: "electronics",
    name: "Electronics",
    icon: "MonitorSmartphone",
    description: "Mobiles, Laptops, Cameras, TVs, etc.",
    subcategories: [
      "Laptop",
      "Camera",
      "TV",
      "Gaming Console",
      "Speaker",
      "Accessories",
      "Smartwatch",
    ],
  },
  {
    id: "mobiles",
    name: "Mobiles",
    icon: "Smartphone",
    description: "Mobile phones, Tablets, Accessories",
    subcategories: [
      "Mobile Phones",
      "Tablets",
      "Accessories",
      "Wearables",
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles",
    icon: "Car",
    description: "Cars, Bikes, Scooters, Commercial",
    subcategories: [
      "Cars",
      "Motorcycles",
      "Scooters",
      "Bicycles",
      "Commercial Vehicles",
      "Spare Parts",
    ],
  },
  {
    id: "furniture",
    name: "Furniture",
    icon: "Sofa",
    description: "Sofas, Beds, Wardrobes, Tables",
    subcategories: [
      "Sofa & Dining",
      "Beds & Wardrobes",
      "Home Decor & Garden",
      "Kids Furniture",
      "Other Household Items",
    ],
  },
  {
    id: "fashion",
    name: "Fashion",
    icon: "Shirt",
    description: "Men, Women, Kids Clothing & Accessories",
    subcategories: [
      "Men",
      "Women",
      "Kids",
      "Watches",
      "Footwear",
      "Bags & Luggage",
    ],
  },
  {
    id: "books",
    name: "Books",
    icon: "BookOpen",
    description: "Fiction, Non-fiction, Academic, Magazines",
    subcategories: [
      "Fiction",
      "Non-fiction",
      "Academic",
      "Magazines",
      "Comics",
    ],
  },
  {
    id: "pets",
    name: "Pets",
    icon: "Dog",
    description: "Dogs, Cats, Birds, Aquariums",
    subcategories: [
      "Dogs",
      "Cats",
      "Birds",
      "Aquariums",
      "Pet Accessories",
      "Other Pets",
    ],
  },
  {
    id: "properties",
    name: "Properties",
    icon: "Home",
    description: "For Rent, For Sale, Commercial",
    subcategories: [
      "For Sale: Houses & Apartments",
      "For Rent: Houses & Apartments",
      "Lands & Plots",
      "For Rent: Shops & Offices",
      "For Sale: Shops & Offices",
      "PG & Guest Houses",
    ],
  },
  {
    id: "jobs",
    name: "Jobs",
    icon: "Briefcase",
    description: "Data entry, Sales, BPO, Marketing",
    subcategories: [
      "Data entry & Back office",
      "Sales & Marketing",
      "BPO & Telecaller",
      "Delivery & Collection",
      "Teacher",
      "Cook",
      "Receptionist & Front office",
      "Operator & Technician",
      "IT Engineer & Developer",
      "Hotel & Travel Executive",
      "Accountant",
      "Designer",
      "Other Jobs",
    ],
  },
  {
    id: "services",
    name: "Services",
    icon: "Wrench",
    description: "Drivers, Tutors, Cleaning, Repairs",
    subcategories: [
      "Education & Classes",
      "Tours & Travel",
      "Electronics & Computer Repair",
      "Health & Beauty",
      "Legal & Documentation",
      "Movers & Packers",
      "Drivers & Taxi",
      "Maids & Domestic Help",
      "Other Services",
    ],
  },
  {
    id: "toys",
    name: "Toys",
    icon: "Gamepad2",
    description: "Action Figures, Board Games, Educational",
    subcategories: [
      "Action Figures",
      "Educational Toys",
      "Board Games",
      "Dolls & Soft Toys",
      "Remote Control Toys",
      "Other Toys",
    ],
  },
];

export const dynamicSpecifications = {
  mobiles: [
    { name: "brand", label: "Brand", type: "text", required: true },
    { name: "storage", label: "Storage (GB)", type: "number", required: true },
    { name: "ram", label: "RAM (GB)", type: "number", required: true },
    { name: "batteryHealth", label: "Battery Health (%)", type: "number", required: false },
    { name: "processor", label: "Processor", type: "text", required: false },
    { name: "screenSize", label: "Screen Size (inches)", type: "number", required: false },
    { name: "imeiAvailable", label: "IMEI Available", type: "checkbox", required: false },
  ],
  vehicles: [
    { name: "brand", label: "Brand", type: "text", required: true },
    { name: "fuelType", label: "Fuel Type", type: "select", options: ["Petrol", "Diesel", "CNG", "Electric", "Hybrid"], required: true },
    { name: "transmission", label: "Transmission", type: "select", options: ["Manual", "Automatic"], required: true },
    { name: "owner", label: "No. of Owners", type: "select", options: ["1st", "2nd", "3rd", "4th+"], required: true },
    { name: "kmDriven", label: "KM Driven", type: "number", required: true },
    { name: "insurance", label: "Insurance Valid Till", type: "date", required: false },
    { name: "rcAvailable", label: "RC Available", type: "checkbox", required: false },
    { name: "registrationYear", label: "Registration Year", type: "number", required: true },
  ],
  properties: [
    { name: "bedrooms", label: "Bedrooms", type: "select", options: ["1", "2", "3", "4", "4+"], required: true },
    { name: "bathrooms", label: "Bathrooms", type: "select", options: ["1", "2", "3", "4+"], required: true },
    { name: "area", label: "Built-up Area (sq.ft)", type: "number", required: true },
    { name: "furnished", label: "Furnishing", type: "select", options: ["Furnished", "Semi-Furnished", "Unfurnished"], required: true },
    { name: "parking", label: "Parking Available", type: "checkbox", required: false },
    { name: "facing", label: "Facing", type: "select", options: ["East", "West", "North", "South", "North-East", "North-West", "South-East", "South-West"], required: false },
  ],
  books: [
    { name: "author", label: "Author", type: "text", required: true },
    { name: "publisher", label: "Publisher", type: "text", required: false },
    { name: "edition", label: "Edition/Year", type: "text", required: false },
    { name: "language", label: "Language", type: "text", required: true },
  ],
  furniture: [
    { name: "material", label: "Material", type: "text", required: false },
    { name: "dimensions", label: "Dimensions (L x W x H)", type: "text", required: false },
    { name: "assemblyRequired", label: "Assembly Required", type: "checkbox", required: false },
    { name: "color", label: "Color", type: "text", required: false },
  ],
};
